### ISSUE TITLE
[BUG] DeserializationSchema::isEndOfStream does not terminate FlinkPulsarSource

### ISSUE THREAD

**Issue by enriched** [streamnative/pulsar-flink#109]
**Describe the bug**
When using a Flink [DeserializationSchema](https://ci.apache.org/projects/flink/flink-docs-release-1.11/api/java/org/apache/flink/api/common/serialization/DeserializationSchema.html) that has overridden the `isEndOfStream` method, the source does not terminate when `isEndOfStream` evaluates to true.

**To Reproduce**
1. Create a DeserializationSchema that returns true for `isEndOfStream`
2. Use FlinkPulsarSource with the schema
3. Stream continues indefinitely

**Expected behavior**
The FlinkPulsarSource closes with a maximum timestamp to flush downstream nodes.

**Additional context**
I am currently attempting to use this in a very simple flink job to export event-time-bounded selections data from pulsar into an S3 bucket. The job will not finalize the file till the stream terminates. If I manually cancel the stream the data shows up in s3.

**Comment by hipstern** [comment]
I'm getting the exact same problem.
