### ISSUE TITLE
[BUG] unable to connect to pulsar source using token with consume permission

### ISSUE THREAD

**Issue by kbarresi** [streamnative/pulsar-flink#111]
**Describe the bug**
I'm trying to use the `FlinkPulsarSource` to connect a simple Flink app to read messages from a persistent Pulsar topic. I'm authenticating using the `org.apache.pulsar.client.impl.auth.AuthenticationToken` plugin, and providing a JWT for a user with `consume` permissions on a specific a topic. 
 
As suggested in the documentation, I create the source and provide a client configuration with authentication:

```java
FlinkPulsarSource<String> source = new FlinkPulsarSource<>(
    adminUrlString, // The admin URL
    clientConfig, // The client config, with auth included
    new SimpleStringSchema(),
    sourceProperties
);
```

Unfortunately, the connector fails with:

```
org.apache.pulsar.client.admin.PulsarAdminException$NotAuthorizedException: HTTP 401 Unauthorized
```
I tracked this down to a rejected call to the admin API at `/admin/v2/persistent/<tenant>/<namespace>/<topic>/partitions`. 

**Expected behavior**
Since the authentication token provided has `consume` permissions for the desired topic, I would expect the `FlinkPulsarSource` to correctly connect and start consuming messages.

Unless I'm missing something, the token used to authenticate will need to be a superuser for the entire tenant? Wouldn't that render `publish`/`consume` authorization at the topic level useless?

**Comment by sijie** [comment]
I am guessing the Flink connector might attempt to create a partitioned topic. @jiazhai Can you help look into this issue?

**Comment by kbarresi** [comment]
This looks like an error on my end! I was supplying a malformed token. The API endpoint itself was returning a "401 - No Authentication" error, which was translated into a "401 Unauthorized" error in the Flink connector.

Upon fixing the token, everything worked as required - the call to `/admin/v2/persistent/<tenant>/<namespace>/<topic>/partitions` successfully ran for the user with `consume` only permissions.

Apologies!

**Comment by sijie** [comment]
@kbarresi Thank you for your update!
