### ISSUE TITLE
Sink data with JSON schema

### ISSUE THREAD

**Issue by rec7y33** [streamnative/pulsar-flink#113]
I use FlinkPulsarSink to sink my object into pulsar topic. however they are in AVRO schema.
Anyway to set them to JSON schema programatically?
Thanks

**Comment by jianyun8023** [comment]
I reviewed this issue and found that `Schema. AVRO` is hard-coded. If it is fixed, it will affect the signature of the constructor and **cause compatibility issues**. 
To fix this problem, I will add builder class to simplify the sink instance.

**Comment by rec7y33** [comment]
yes, I have actually modified that function to return json schema instead and built it locally. appreciate an update to make json schema possible. thanks!

**Comment by rec7y33** [comment]
hello please add this into version 1.11.1 as well. thanks~

**Comment by sijie** [comment]
@jianyun8023 Can you double-check if this feature is in Flink 1.11 support.

**Comment by jianyun8023** [comment]
> hello please add this into version 1.11.1 as well. thanks~

I opened an issue to solve this problem. #145
