### ISSUE TITLE
How to subscribe to pattern topic?

### ISSUE THREAD

**Issue by rec7y33** [streamnative/pulsar-flink#114]
How can I subscribe to a pattern like public/default/aaa.*

**Comment by jianyun8023** [comment]
You can refer to  [pulsar-source](https://github.com/streamnative/pulsar-flink#pulsar-source)，use `topicsPattern`.
example:
```java
StreamExecutionEnvironment see = StreamExecutionEnvironment.getExecutionEnvironment();
Properties props = new Properties();
props.setProperty("topicsPattern", "persistent://prop/use/ns-abc/pattern-topic-.*")
FlinkPulsarSource<String> source = new FlinkPulsarSource<>(serviceUrl, adminUrl, new SimpleStringSchema(), props);

DataStream<String> stream = see.addSource(source);

// chain operations on dataStream of String and sink the output
// end method chaining

see.execute();
```

**Comment by rec7y33** [comment]
I see, I can see that the topics are added into the reader, however when I try to print the data, nothing happened, what did I do wrong? 
Heres the snippet:

`
StreamExecutionEnvironment see = StreamExecutionEnvironment.getExecutionEnvironment();
see.getConfig().setAutoWatermarkInterval(1000);
see.getConfig().setParallelism(parallelism);
Properties props = new Properties();
FlinkPulsarSource<String> fps = new FlinkPulsarSource<>(serviceUrl, adminUrl, new SimpleStringSchema(), props);
        
DataStream<String> stream = see.addSource(fps);
SingleOutputStreamOperator<Void> result = stream.flatMap(new IgniteProcess());
`

`
final class IgniteProcess extends RichFlatMapFunction<String, Void> implements FlatMapFunction<String, Void> {
    IgniteHelper ih;
    Logger log;
    public IgniteProcess() {
    }

    @Override
    public void open(Configuration parameters) {
        if(log == null){
            log = LoggerFactory.getLogger(IgniteProcess.class);
        }
    }

    @Override
    public void flatMap(String lo, Collector<Void> collector) {
        System.out.println("String: " + lo);
        log.info("String" + lo);
    }
}
`

![image](https://user-images.githubusercontent.com/20633396/89772500-adddd480-db34-11ea-9978-54a47fc2f624.png)

**Comment by jianyun8023** [comment]
After your flink is started, is it possible to send messages to the pulsar topic?

**Comment by rec7y33** [comment]
yes. in fact there are scripts sending messages to these topics constantly. I am able to see them using pulsar sql.

**Comment by jianyun8023** [comment]
Have you set up a flink sink?
For example, simply print it out
```java
        SingleOutputStreamOperator<Void> result = stream.flatMap(new IgniteProcess());
        result.print();
        see.execute();
```

If sink is not set, the stream process will not run.

**Comment by jianyun8023** [comment]
Is your problem solved?

**Comment by rec7y33** [comment]
Yes, I am able to read from the topics and print the data now. However, i can see that the reader subscribes to the topics one by one and it is taking a very long time before it starts reading the data. I have hundreds of topics within the given pattern. Is this normal? or is there a way that I can speed up the subscribing process? Thanks

**Comment by jianyun8023** [comment]
It is recommended to increase the degree of parallelism for the job of flink
