### ISSUE TITLE
[FEATURE] Use custom MessageRouting to publish messages to partition topics

### ISSUE THREAD

**Issue by rec7y33** [streamnative/pulsar-flink#121]
Hello, what do I need to do to sink to partitioned topics with custom partition routing mode?
https://pulsar.apache.org/docs/en/next/cookbooks-partitioned/

Thank you.

**Comment by jiazhai** [comment]
@jianyun8023 would you please help answer this question and add related doc?

**Comment by jianyun8023** [comment]
> @jianyun8023 would you please help answer this question and add related doc?

Okay, the documentation for the connector is really not enough, I will add the documentation.

**Comment by jianyun8023** [comment]
It does not currently support setting `messageRoutingMode(MessageRoutingMode.SinglePartition)` to select the partition to which the message is sent.

```java
String pulsarBrokerRootUrl = "pulsar://localhost:6650";
String topic = "persistent://my-tenant/my-namespace/my-topic";

PulsarClient pulsarClient = PulsarClient.builder().serviceUrl(pulsarBrokerRootUrl).build();
Producer<byte[]> producer = pulsarClient.newProducer()
        .topic(topic)
        .messageRoutingMode(MessageRoutingMode.SinglePartition)
        .create();
producer.send("Partitioned topic message".getBytes());
```

**Comment by jiazhai** [comment]
@jianyun8023 if this is supported, we should update the readme and docs

**Comment by jianyun8023** [comment]
Custom MessageRouting is currently not supported. Thank you for your suggestion. Support will be added in subsequent versions.

**Comment by reswqa** [comment]
in https://github.com/streamnative/pulsar-flink/pull/209,This feature is supported by the way.
