### ISSUE TITLE
extract-commom

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#128]
**Is your feature request related to a problem? Please describe.**
To support two flink versions, two modules are used, and their common parts are not extracted, which leads to the complexity of Pulsar's new feature support.

**Describe the solution you'd like**
Extract the common part and add the `common` module.

**Describe alternatives you've considered**
small steps and gradually complete the extraction of the public part

**Additional context**

see [support Flink 1.11 and using flink-sql DDL to operate with pulsar](https://github.com/streamnative/pulsar-flink/pull/115)

**Comment by jiazhai** [comment]
related with the segment reader issue
