### ISSUE TITLE
[BUG] topic-partition-offset-states_subName State memory leak

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#135]
**Describe the bug**
We are seeing the below err in the flink pulsar connector use case
2020-09-16 11:44:39.764 [Source: opr_event -> (opr_event_monitoring, invalid_data_topic_monitoring, Sink: invalid_data_topic, String_to_JsonNode -> filtered-input-stream -> (XXXX-Analytics-Event-Correlation 
-XXX-filter_monitoring, mapped-input-stream -> XXXX-Analytics-Event-Correlation-XXX-mapper_monitoring)) (7/8)] DEBUG org.apache.flink.runtime.state.TaskStateManagerImpl - Operator 140d9cc943c079ec895d010fe 
c9ee23b has remote state SubtaskState{operatorStateFromBackend=StateObjectCollection{[OperatorStateHandle{stateNameToPartitionOffsets={topic-partition-offset-states_subName=StateMetaInfo{offsets=[1106, 1127 
, 1148, 1169, 1190, 1211, 1232, 1253, 1274, 1295, 1316, 1337, 1358, 1379, 1400, 1421, 1442, 1463, 1484, 1505, 1526, 1547, 1568, 1589, 1610, 1631, 1652, 1673, 1694, 1715, 1736, 1757, 1778, 1799, 1820, 
   it has like this million of records. and the state restoration is not happening .can you please confirm weather the purge is happening or not on offsets.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
pulsar-flink connector 2.4.28
pulsar-flink connector 2.5.0、2.5.1 for flink 1.9

**Comment by codelipenghui** [comment]
@jianyun8023 Can we close this issue? I noticed #131 has fixed it right?

**Comment by jianyun8023** [comment]
fixed
