### ISSUE TITLE
[BUG] AlreadyClosedException in the Pulsar client at the start of a Flink Stream

### ISSUE THREAD

**Issue by mathieudruart** [streamnative/pulsar-flink#140]
**Describe the bug**
We are trying to start a Flink Stream using the flink-connector, but there seem to be an issue with the CachedPulsarClient (AlreadyClosedException on the pulsar client of the FlinkPulsarSink).

**To Reproduce**
The Flink Stream have 2 sources (2 FlinkPulsarSource) and a FlinkPulsarSink as output. Both FlinkPulsarSource instanciate a PulsarClient in the CachedPulsarClient (one per source, no matter the parallelism value), the FlinkPulsarSink instanciates one PulsarClient per slot used (3 instances with a parallelism set to 3). The CachedPulsarClient have a maximum cache size of 5 by default, so until a parallelism of 3 there is no issue (1 client for each source, and 3 clients for the sink), but when the parallelism is set to a greater value than the size of the cache, we have this exception :

    Caused by: org.apache.pulsar.client.api.PulsarClientException$AlreadyClosedException: Client already closed : state = 
    Closing
    	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:870)
    	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:93)
    	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSinkBase.createProducer(FlinkPulsarSinkBase.java:264)

The client appears to be closed while still in use. We tried to change the clientcachesize parameter to increase the number of clients stored in the cache, but the parameter doesn't seem to work (only 5 clients seem to be stored while debugging), just a guess : the setCacheSize method on the CachedPulsarClient set a static value but as the guavaCache is also a static value of the same class, it's already set before the cacheSize could be changed.

Anyway, we don't know if increasing the clientcachesize should be a real good solution or if a single client should be reused from the cache across all the different tasks ?

**Expected behavior**
No AlreadyClosedException at the start of the stream.

**Additional context**
- flink-pulsar 2.5.3
- flink 1.11.1
- Scala 2.12
- Pulsar 2.6.0 cluster

**Comment by sijie** [comment]
@jianyun8023 can you take a look at this issue?

**Comment by jianyun8023** [comment]
> @jianyun8023 can you take a look at this issue?

Well, I will deal with it as soon as possible.

**Comment by jianyun8023** [comment]
I have confirmed the problem and it is being fixed. But I need to take two days off, and I will submit pr at the end of the holiday.
