### ISSUE TITLE
[docs] Update docs on how to work with Flink 1.11 in Pulsar

### ISSUE THREAD

**Issue by Jennifer88huang** [streamnative/pulsar-flink#163]
Hey!
does anyone able to make pulsar-flink work together?

Addison Higham  
are you using https://github.com/streamnative/pulsar-flink ?
streamnative/pulsar-flink
Elastic data processing with Apache Pulsar and Apache Flink
Stars
81
Language
Java
<https://github.com/streamnative/pulsar-flink|streamnative/pulsar-flink>streamnative/pulsar-flink | Jul 9th, 2019 | Added by GitHub

Roee Hershko  
i tried to use it, couldnt make it work,
pulsar client keep getting closed after the first time it finish consuming.
also the "FlinkPulsarSource" class from teh examples doesn't exists (edited) 

Addison Higham  
do you have checkpointing enabled?

Roee Hershko 
yes

Roee Hershko 
        // parse input arguments
        final ParameterTool parameterTool = ParameterTool.fromArgs(args);
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.getConfig().disableSysoutLogging();
        env.getConfig().setRestartStrategy(RestartStrategies.fixedDelayRestart(4, 10000));
        env.enableCheckpointing(5000);
        env.getConfig().setGlobalJobParameters(parameterTool);
        env.setStreamTimeCharacteristic(TimeCharacteristic.ProcessingTime);
        String serviceUrl = "pulsar://192.168.49.2:30714";
        String inputTopic = "persistent://public/default/input-1";
        String subscription = "flink-examples";
        String outputTopic = "output-1";
        int parallelism = parameterTool.getInt("parallelism", 1);
        System.out.println("Parameters:");
        System.out.println("\tServiceUrl:\t" + serviceUrl);
        System.out.println("\tInputTopic:\t" + inputTopic);
        System.out.println("\tSubscription:\t" + subscription);
        System.out.println("\tOutputTopic:\t" + outputTopic);
        System.out.println("\tParallelism:\t" + parallelism);
        PulsarSourceBuilder<String> builder = PulsarSourceBuilder.builder(new SimpleStringSchema())
            .serviceUrl(serviceUrl)
            .topic(inputTopic)
            .subscriptionName(subscription);
        SourceFunction<String> src = builder.build();
        DataStream<String> input = env.addSource(src);
        input
            .map(new MapFunction<String, String>() {
                @Override
                public String map(String s) throws Exception {
                    return s;
                }
            })
            .print();
        env.execute("Pulsar Stream WordCount");
 
this is my code so far (edited) 

sijieg 
which version are you using?
@Jianyun Zhao @hangc can probably help.

Roee Hershko  
Latest I think it's 2.5.2

Roee Hershko  
I was able to make it work eventually but I used different source class - PulsarFlinkSource
So the builder is deprecated?

sijieg  
I see. Are you using Flink 1.11? If so, I guess that’s probably the case. Because there is a refactor to support both Flink 1.9 and Flink 1.11. We might need to update our documentation to reflect it. 

Roee Hershko  
Ahh I see, thanks for helping!
I have 1 more question, does pulsar provide event time to flink?
When I used kafka, kafka automatically generated timestamp, does pulsar generate message timestamps? I saw you have event time in the docs but couldn't find a way to fetvh it in flink or provide it with pulsar client.
I have demo to show tomorrow hopefully I will be able to make it working by then (edited) 

hangc  
@Roee Hershko You’d better try to use https://github.com/streamnative/pulsar-flink pulsar-flink-connector. In your demo code, that seems pulsar/pulsar-flink.
streamnative/pulsar-flink
Elastic data processing with Apache Pulsar and Apache Flink
Stars
81
Language
Java
<https://github.com/streamnative/pulsar-flink|streamnative/pulsar-flink>streamnative/pulsar-flink | Jul 9th, 2019 | Added by GitHub
New

hangc  
In streamnative pulsar-flink-connector, the message has __publishTime that represents message timestamp, you can generate your own message deserializer to get the message timestamp.

**Comment by roee-hershko** [comment]
code above still gets an error "Null Pointer", something about the processing time/watermark

**Comment by jianyun8023** [comment]
The task moved #183
