### ISSUE TITLE
[FEATURE] Make pulsar sink work better

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#174]
**Is your feature request related to a problem? Please describe.**

The implementation of sink is too rigid, which makes it difficult to meet the actual needs of users. Writes use string, kv or bytes for example.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by reswqa** [comment]
We can use the new ser/deSer schema to solve this problem, it should be possible to close this issue
