### ISSUE TITLE
[FEATURE] An integrated solution for pulsar Schema and Flink

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#177]
**Is your feature request related to a problem? Please describe.**
Since the Pulsar connector did not adhere to the Flink format standard, this resulted in the maintenance of schema conversions, data structure conversions, etc. This part of the code was very difficult for me to maintain, and it was difficult for new people to participate in this part of the work. The FlinkPulsarRowSink and FlinkPulsarRowSource feature implementations.

Another important reason is due to the lack of Sink for Format, which may affect the progress of the merge back into the community.

**Describe the solution you'd like**
- **plan 2:**  Flink Avro, JSON Format are all standard formats that can be easily integrated with Pulsar. Let the user freely use Flink Avro, JSON, etc. format, and we generate Pulsar Schema information when the user uses Avro, JSON, etc.  
When new serialization methods are supported in Pulsar, we can easily add or use the flink format.

**Describe alternatives you've considered**

- **plan 1:** Create a pulsar format and give the user the option to use it. We need to maintain the conversion relationship between Flink data types and Pulsar data types, which is not easy.

**Additional context**

Pulsar has its own Schema, which supports serialization, deserialization with POJO data.
Flink also has a Format function that supports serialization and deserialization of data.

When using the Flink format, the data written to or read from Pulsar is bytes, we can use `AutoProduceBytesSchema` to produce the message, which allows us to wrap the real Schema information in bytes and will check that the bytes data is properly scrubbed.

**Comment by jianyun8023** [comment]
plan 1 #172

**Comment by jianyun8023** [comment]
I think Plan 2 is feasible, [flink-avro](https://github.com/apache/flink/tree/master/flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro) uses the standard avro and can be combined with Pulsar. If avro has been enhanced in Pulsar, we can refer to [flink-avro-confluent-registry](https://github.com/apache/flink/tree/master/flink-formats/flink-avro-confluent-registry/src/main/java/org/apache/flink/formats/avro/registry/confluent)

**Comment by jianyun8023** [comment]
@sijie What do you think of this program? 
For existing Pulsar serialization and deserialization using the capabilities of Pulsar itself. I guess the reason for doing this earlier is that in Flink Table mode, it is not always possible to get the data type of Table. As of Flink 1.11, it must be possible to get the data type when creating a Table instance.

**Comment by reswqa** [comment]
I strongly agree that if it can be combined with Flink's format, it will greatly reduce our complex maintenance work. Furthermore, our project now has some fatal problems with the schema implementation, causing FlinkSQL to fail in some cases. By the way, I am very interested in this feature and can contribute to it.

**Comment by jianyun8023** [comment]
One of the problems that has been discovered now, the flink avro package path is not the same as the pulsar avro path, we are using `pulsar-client-all`. I think we can replace it with `pulsar-client-origin` and we handle jar shaded.

**Comment by jianyun8023** [comment]
Now determine the real-time scenario, according to plan 2 and go further. Serialization and deserialization using flink format. flink provides the ability to convert sql DataType to an avro schema, which we use. Now all we need to do is write the avro schema to pulsar when using the avro, json format.
Now we don't need to maintain complex serialization, schema relationships. We just need to make sure that the schema and data produced by flink is compatible with pulsar. Also pulsar provides data validation for reading and writing messages, which is great.

As a connector, it should be guaranteed to be simple enough.

**Comment by jianyun8023** [comment]
Referring to the FLIP-107 and Kafka implementations, we will implement an adaptive serialization and deserialization interface, which will contain the serialization components for external inputs, Pulsar Schema generation. The responsibilities in the Sink interface will be further simplified and the redundant implementation classes will be removed.


The responsibilities of the components in the current Pulsar connector are not clear. So many implementations of FlinkPulsarRowSource, ReaderThread, RowReaderThread, PulsarFetcher, RowReaderThread, etc. The Flink Row type is enabled and replaced by the RowData type.

**Comment by jianyun8023** [comment]
Final Solution: **Wrap the Flink format instance as an implementation of the Pulsar Schema interface**. This satisfies the Flink format specification and meets Pulsar's expectations.
