### ISSUE TITLE
Flink Version Support Program

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#181]
The code we have merged into the community is primarily based on Flink 1.12. Older versions of Flink connectors that are now supported are as follows

- Flink 1.9-1.10    The api in this version is very different from the new version, and support for the new features requires more effort.
- Flink 1.11    The known differences between it and the new version are mainly in the FLIP-107 metadata processing.

We need to identify the programs we support.

**Comment by reswqa** [comment]
I could try to implement some of the changes we introduced recently on 1.11, but 1.9 will take some time to do. As far as I'm concerned, version 1.9 is hard for us to maintain later.

**Comment by jianyun8023** [comment]
We now plan to maintain the latest version of master. flink 1.9 and 1.11 will be separated from master and maintained as a separate branch.
