### ISSUE TITLE
[BUG] org.apache.pulsar.shade.org.apache.bookkeeper.common.util not found

### ISSUE THREAD

**Issue by xiaoyan5686670** [streamnative/pulsar-flink#182]
**Describe the bug**
Maybe it is not a bug
version is pulsar-flink-master
When I use the CatalogITest class to test, an error is reported
`org.apache.pulsar.shade.org.apache.bookkeeper.common.util` not found

**Screenshots**
![image](https://user-images.githubusercontent.com/22173082/100092617-54a27280-2e91-11eb-9cc2-d1b889f3be99.png)

How can i fix it

**Comment by jianyun8023** [comment]
Sorry I didn't update this section, but you need to run `mvn -pl managed-ledger-shaded install` to install managed-ledger-shaded to your local repository first. Then you need to disable the managed-ledger-shaded module in maven.

![image](https://user-images.githubusercontent.com/18240360/100093765-f24a7180-2e92-11eb-95f9-90eab197c8f8.png)
![image](https://user-images.githubusercontent.com/18240360/100093822-04c4ab00-2e93-11eb-8927-9b84c3fc1b09.png)

**Comment by jianyun8023** [comment]
We need to update the README, it must be available.

**Comment by xiaoyan5686670** [comment]
thank u

**Comment by reswqa** [comment]
thanks @jianyun8023  for solve this problem.
