### ISSUE TITLE
[BUG]  Update the README to make sure it is available.

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#183]
**Describe the bug**
Update the README to make sure it is available.
The problem we know now is the build project part, the SQL part.

We have found that many problems are caused by poor support for the Flink serialization mechanism. We are doing our best to solve it.

**Comment by reswqa** [comment]
Due to branching differences, we may have to maintain different readme files.

**Comment by jianyun8023** [comment]
master has been updated. #192
