### ISSUE TITLE
[BUG]Caused by: java.io.NotSerializableException: org.apache.flink.streaming.connectors.pulsar.internal.JacksonRecordParser$FailureSafeRecordParser

### ISSUE THREAD

**Issue by xiaoyan5686670** [streamnative/pulsar-flink#185]
**Describe the bug**
may be is not bug.
Exception in thread "main" org.apache.flink.api.common.InvalidProgramException: The implementation of the FlinkPulsarSource is not serializable. The object probably contains or references non serializable fields.
Caused by: java.io.NotSerializableException: org.apache.flink.streaming.connectors.pulsar.internal.JacksonRecordParser$FailureSafeRecordParser

**To Reproduce**
1. sourcecode:
`import org.apache.flink.runtime.state.StateBackend
import org.apache.flink.runtime.state.filesystem.FsStateBackend
import org.apache.flink.streaming.api.scala.StreamExecutionEnvironment
import org.apache.flink.table.api.{EnvironmentSettings, SqlDialect}
import org.apache.flink.table.api.bridge.scala.StreamTableEnvironment

object PulsarTestSql2 {
  def main(args: Array[String]): Unit = {
    val bsEnv = StreamExecutionEnvironment.getExecutionEnvironment
    val bsSettings = EnvironmentSettings.newInstance.useBlinkPlanner.inStreamingMode.build
    val bsTableEnv = StreamTableEnvironment.create(bsEnv, bsSettings)
    bsEnv.enableCheckpointing(5000)
    val backend = new FsStateBackend("file:///c/tmp/", true)
    bsEnv.setStateBackend(backend.asInstanceOf[StateBackend])
    bsTableEnv.getConfig.setSqlDialect(SqlDialect.DEFAULT)
    bsTableEnv.executeSql("SHOW CATALOGS").print
    bsTableEnv.executeSql("SHOW tables").print

    val source_ddl2 =
      """create table test_flink_sql(
        `name` string,
        sex string
      ) with (
      'connector.type' = 'pulsar',
    'connector.version' = '1',
    'connector.topic' = 'persistent://my-tenant/my-namespace/qxy4',
    'connector.service-url' = 'pulsar://localhost:6650',
    'connector.admin-url' = 'http://localhost:8080',
    'connector.startup-mode' = 'earliest',  //订阅模式
    'connector.properties.0.key' = 'pulsar.reader.readerName', //参数名
    'connector.properties.0.value' = 'test_flink_sql_v1',      // 参数值
    'connector.properties.1.key' = 'pulsar.reader.subscriptionRolePrefix',
    'connector.properties.1.value' = 'test_flink_sql_v1',
    'connector.properties.2.key' = 'pulsar.reader.receiverQueueSize',
    'connector.properties.2.value' = '1000',
    'connector.properties.3.key' = 'partitiondiscoveryintervalmillis', //参数名
    'connector.properties.3.value' = '5000',                           //参数值
    'format.type' = 'json',
	'format.derive-schema' = 'true',
	'format.ignore-parse-errors' = 'true',
    'update-mode' = 'append'
    ) """.stripMargin

    bsTableEnv.executeSql(source_ddl2)

    val sink_ddl =
      """
        |CREATE TABLE print_table (
        | name STRING,
        | sex string
        |) WITH (
        | 'connector' = 'print'
        |)
        |""".stripMargin
        bsTableEnv.executeSql(sink_ddl)
    val sql =
      """ insert into print_table  select *
        | from test_flink_sql
        | """.stripMargin
        bsTableEnv.executeSql(sql)

  }
}

`
sourcedata:
`import org.apache.pulsar.client.api.Producer;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.PulsarClientException;
import org.apache.pulsar.client.api.Schema;
import org.apache.pulsar.client.impl.schema.JSONSchema;
import qxy.type.Student;

public class ProducePojo {
    public static void main(String[] args) throws PulsarClientException {
        PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build();

        Producer<Student> producer = client.newProducer(Schema.JSON(Student.class))
                .topic("persistent://my-tenant/my-namespace/qxy4")
                .create();
//        Producer<String> producer = client.newProducer(Schema.STRING)
//                .topic("persistent://my-tenant/my-namespace/qxy4")
//                .create();

// You can then send messages to the broker and topic you specified:
        Student user = new Student("qxy3", "ll");

        producer.send(user);

        producer.close();
        client.close();
    }
}
`
2. Click on 'Run'

3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22173082/100407228-c9003000-30a2-11eb-9138-b3470a3080bf.png)
![image](https://user-images.githubusercontent.com/22173082/100407260-e0d7b400-30a2-11eb-8f6f-1a5ff0aeef52.png)

**Comment by reswqa** [comment]
I'm so sorry to tell you that our formal version have some problems in SQL. we have already fixed it, and plan to release new version in this weekend. Thanks for your feekback.

**Comment by jianyun8023** [comment]
please update to  `2.5.5` or `2.5.6`. 

```xml
<dependency>
 <groupId>io.streamnative.connectors</groupId>
  <artifactId>pulsar-flink-connector-2.11-1.11</artifactId>
  <version>2.5.5</version>
</dependency>

<dependency>
 <groupId>io.streamnative.connectors</groupId>
  <artifactId>pulsar-flink-connector-2.12-1.11</artifactId>
  <version>2.5.6</version>
</dependency>
```

**Comment by xiaoyan5686670** [comment]
thank u 










At 2020-12-04 20:05:51, "Jianyun Zhao" <notifications@github.com> wrote:

please update to 2.5.5 or 2.5.6.

<dependency>
 <groupId>io.streamnative.connectors</groupId>
  <artifactId>pulsar-flink-connector-2.11-1.11</artifactId>
  <version>2.5.5</version>
</dependency>

<dependency>
 <groupId>io.streamnative.connectors</groupId>
  <artifactId>pulsar-flink-connector-2.12-1.11</artifactId>
  <version>2.5.6</version>
</dependency>

**Comment by xiaoyan5686670** [comment]
> please update to `2.5.5` or `2.5.6`.
> remove 'format.ignore-parse-errors' = 'true' to sql param.
> 
> ```
> <dependency>
>  <groupId>io.streamnative.connectors</groupId>
>   <artifactId>pulsar-flink-connector-2.11-1.11</artifactId>
>   <version>2.5.5</version>
> </dependency>
> 
> <dependency>
>  <groupId>io.streamnative.connectors</groupId>
>   <artifactId>pulsar-flink-connector-2.12-1.11</artifactId>
>   <version>2.5.6</version>
> </dependency>
> ```

Dear:
       After updating, a new error is reported

      `org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Student': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"Student(name=qxy3, sex=ll)"; line: 1, column: 9]`
   
     producer
    `    public static void main(String[] args) throws PulsarClientException {
        PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build();

        Producer<Student> producer = client.newProducer(Schema.JSON(Student.class))
                .topic("persistent://my-tenant/my-namespace/qxy4")
                .create();

        Student user = new Student("qxy3", "ll");

        producer.send(user);

        producer.close();
        client.close();
    }`

`
public class Student {
    private  String name;
    private  String sex;

}`
What should I modify to make it work

thank u

**Comment by reswqa** [comment]
@xiaoyan5686670 
Is this pular topic new or has it existed before, I'm a little worried about the schema from the old pulsar-flink connector version if it was used before. I've reproduced your logic in my environment and it works fine.

`      String table = "topic" + UUID.randomUUID();
        String tableName = TopicName.get(table).getLocalName();
        PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build();

        Producer<Student> producer = client.newProducer(Schema.JSON(Student.class))
                .topic(tableName)
                .create();

        Student user = new Student("aaa", "male");

        producer.send(user);

        producer.close();
        client.close();


        StreamExecutionEnvironment see = StreamExecutionEnvironment.getExecutionEnvironment();
        see.setParallelism(1);
        StreamTableEnvironment tEnv = StreamTableEnvironment.create(see);

        String source_ddl2 =
                String.format(
                        "create table pulsar (\n" +
                                "  name string, \n" +
                                "  sex string \n" +
                                ") with (\n" +
                                "  'connector.type' = 'pulsar',\n" +
                                "  'connector.topic' = '%s',\n" +
                                "  'connector.service-url' = '%s',\n" +
                                "  'connector.admin-url' = '%s',\n" +
                                "  'connector.startup-mode' = 'earliest', \n" +
                                " 'update-mode' = 'append', \n" +
                                "  %s \n" +
                                ")",
                        tableName,
                        "pulsar://localhost:6650",
                        "http://localhost:8080",
                        String.format("'format.type' = '%s'", "json"));
        tEnv.executeSql(source_ddl2);
        String sink_ddl = "" +
                "CREATE TABLE print_table ( \n" +
                "name STRING, \n" +
                "sex string \n" +
                ") with ( 'connector' = 'print' )";

        tEnv.executeSql(sink_ddl);
        String sql =
                " insert into print_table select * \n" +
                        "from pulsar \n ";
        tEnv.executeSql(sql);
`

The above is my code, so you can see if it is consistent with your need.by the way i use
`<pulsar.version>2.5.2</pulsar.version>
  <scala.binary.version>2.11</scala.binary.version>
  <flink.version>1.11.1</flink.version>`

**Comment by xiaoyan5686670** [comment]
@reswqa 
I have completed the test and can now run normally.
reason :
As you said “Is this pular topic new or has it existed before, I'm a little worried about the schema produced by the old pulsar-flink connector version may cause some problem if the topic was used before.”
thank u .
