### ISSUE TITLE
部署太费劲，总是报错。。。代码是不是有问题？

### ISSUE THREAD

**Issue by fi-ecavc** [streamnative/pulsar-flink#22]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jiazhai** [comment]
@fi-ecavc You opened an issue contains nothing. What is your environment and steps? And what is the error?

**Comment by jiazhai** [comment]
close this issue since no information is provided.  @fi-ecavc Please feel free to open it and provide more detailed information.
