### ISSUE TITLE
failOnDataLoss doesn't seem to cause failure when it's supposed to

### ISSUE THREAD

**Issue by mrbazzik** [streamnative/pulsar-flink#235]
**Reproduce:**
Connector version: `pulsar-flink-2.12-1.11.1/2.5.3`
- Use a persistent Pulsar topic as a source for Flink job
- Create a savepoint for the Flink job and stop it
- Wait till the message corresponding to the job's stored offset is deleted from the topic due to retention policy
- Restore the job from the savepoint with `failOnDataLoss=true` (default)

**Observed behaviour:**
Job doesn't fail. In the logs it seems like it restores the non-existing offset but then silently proceeds to the earliest messages in the topic (topic is not empty)

**Expected behaviour:**
I'd assume that with `failOnDataLoss=true` (default) it should fail with "Potential data loss..." error.
I wonder if it has something to do with the logic here: https://github.com/streamnative/pulsar-flink/blob/4e7cb381c0a913d57218523315059f6dabdcb4de/pulsar-flink-1.11/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/ReaderThread.java#L149

**Comment by codelipenghui** [comment]
@jianyun8023 Could you please help take a look at this issue?

**Comment by jianyun8023** [comment]
It's a bug, and his role is weakened in the new version. I will fix it next as soon as possible.

**Comment by mrbazzik** [comment]
thanks for confirming!
