### ISSUE TITLE
[BUG] create ddl with external-subscription does not work

### ISSUE THREAD

**Issue by pyramidsphinx** [streamnative/pulsar-flink#239]
**Describe the bug**
Use the ddl sql 

create table pulsar(
  id int,
  name string
) with (
  'connector'='pulsar',
  'topic'='XXX',
  'service-url'='XXX',
  'admin-url'='XXX',
  'scan.startup.mode'='external-subscription',
  'scan.startup.sub-name'='test',
 'properties.scan.startup.mode'='earliest',
 'format'='avro'
)

query sql
select id from pulsar

with the  scan.startup.mode is 'external-subscription'  , the query sql consume nothing

with the scan.startup.mode=earliest , it can consume from earliest

connector using 
pulsar-flink-connector-2.12-1.12-2.7.1.jar

**Comment by jianyun8023** [comment]
Please add the following information such as the connector version and flink version used.

**Comment by pyramidsphinx** [comment]
connector version is
 pulsar-flink-connector-2.12-1.12-2.7.1.jar

**Comment by jianyun8023** [comment]
You delete the `properties.scan.startup.mode'='earliest'` configuration, which conflicts with `scan.startup.mode'='external-subscription`.

**Comment by pyramidsphinx** [comment]
how can I subscribe from from earliest using the external-subscription 
like 
source.setStartFromSubscription("test", MessageId.earliest)
using ddl

**Comment by pyramidsphinx** [comment]
but the checkpoint seems not take effect
StreamingExecutionEnvironment see=StreamingExecutionEnvironment.getExecutionEnvironment();
see.enableCheckpointing(1000)
source.setStartFromSubscription("test",MessageId.earliest)

with chekpoint it can realize consume exactly once


but with sql

create table pulsar(
id int,
name string
) with (
'connector'='pulsar',
'topic'='XXX',
'service-url'='XXX',
'admin-url'='XXX',
'scan.startup.mode'='external-subscription',
'scan.startup.sub-name'='test',
'properties.connector.sub-default-offset'='earliest',
'format'='avro'
)

with the parameter 'properties.connector.sub-default-offset'='earliest',

it can subscribe like source.setStartFromSubscription("test",MessageId.earliest)

StreamingExecutionEnvironment see=StreamingExecutionEnvironment.getExecutionEnvironment();
see.enableCheckpointing(1000);
StreamTableEnvironment tEnv=StreamTableEnvironment.create(see);

String query="select id from pulsar";
DataStream<RowData> result=tEnv.toAppendStream(tEnv.sqlQuery(query),RowData.class);

result.print()
the checkpoint seems not tabke effect ;
it can not  consume exactly-once , it consume from the earliest every time

**Comment by jianyun8023** [comment]
Well, sorry, now under sql, the consumption location of the subscription schema can only be latest. but it is possible to submit an issue for a new feature to support this feature.

**Comment by jianyun8023** [comment]
@pyramidsphinx Are you still paying attention? This pr is solving it. https://github.com/streamnative/pulsar-flink/pull/349

**Comment by syhily** [comment]
Closed for outdated. @pyramidsphinx You can PING me if this issue hasn't be solved.
