### ISSUE TITLE
[FEATURE] the sql ddl support exactly once

### ISSUE THREAD

**Issue by pyramidsphinx** [streamnative/pulsar-flink#250]

**Comment by jianyun8023** [comment]
Now in flink version 1.12, sql already supports source, sink's exactly once

**Comment by pyramidsphinx** [comment]
how to write the sql    ， to support source exactly once

**Comment by jianyun8023** [comment]
With checkpoint on, source is working in exact once mode

**Comment by V1ncentzzZ** [comment]
Hi @jianyun8023 Does pulsar support transcation currently?

**Comment by jianyun8023** [comment]
> Hi @jianyun8023 Does pulsar support transcation currently?

When Pulsar version is greater than 2.7.0, sink is supported for transactions. You can check the repository readme for a description of all this.
