### ISSUE TITLE
[BUG] Avro schema decode errors when working with partitioned topics + ddl

### ISSUE THREAD

**Issue by seeday** [streamnative/pulsar-flink#251]
**Describe the bug**
When using avro schema, partitioned topics, and sql ddl, the messages will not be parsed correctly causing the job to crash. The issue does not appear when using non-partitioned topics, but may be triggered in other cases like json schema, catalog, or others. The issue also doesn't seem to appear unless the jar is deployed to a flink cluster. 

I believe this is a race condition of some sort when deserializing messages. The avro deserializers are not thread safe, and I believe the buffer is being replaced underneath a message as it's being parsed. I've made some changes to `emitRecord` in `ReaderThead.java` that seem to patch the issue, but I didn't open those changes as a pull request because it's a bit of a hack and not a real solution. A real solution would likely have a per-thread deserializer, but I wasn't entirely sure how to fit that change into the rest of the architecture (mostly having to deep-clone a `PulsarDeserializer` object).

**To Reproduce**
1. Create a partitioned topic with an avro schema, send some messages
2. Create a flink cluster (local via start-cluster.sh seems to reproduce the issue just fine)
3. Create a job that uses sql ddl to read messages from the pulsar topic
4. deploy the job to the cluster
5. Receive avro schema decode errors

**Expected behavior**
The topic is consumed correctly.

**Patch**
```java
   // ReaderThread.java:200
   protected void emitRecord(Message<T> message) throws IOException {
        MessageId messageId = message.getMessageId();
        T         record;
        synchronized (deserializer) {
            record = deserializer.deserialize(message);
            if (deserializer.isEndOfStream(record)) {
                running = false;
                return;
            }
        }
        owner.emitRecordsWithTimestamps(record, state, messageId, message.getEventTime());
    }
```

**Comment by jianyun8023** [comment]
What are the versions of Flink, pulsar, and connector you are using?

**Comment by seeday** [comment]
Flink 1.12.1, connector 2.7.3, pulsar 2.6.1
