### ISSUE TITLE
[FEATURE] Get messageID of the message produced

### ISSUE THREAD

**Issue by rec7y33** [streamnative/pulsar-flink#257]
Hi, is it possible to retrieve the message id of a produced message using FlinkPulsarSink ? 
Thanks

**Comment by jianyun8023** [comment]
This is not accessible right now. What kind of problem are you trying to solve?

**Comment by syhily** [comment]
The `SinkFunction` interface on the flink side wouldn't have any `SideOutput`. We don't know how to add this ability. Or print debug a log?

**Comment by syhily** [comment]
Close the issue for no response from @rec7y33, you can ping me if you still want this feature. We can reopen this issue and discuss on it.
