### ISSUE TITLE
[BUG] Remove flink-protobuf code from the project 

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#270]
**Describe the bug**

Remove the code from the project when flink-protobuf has a package available.

Code that introduces `flink-protobuf` because it supports Protobuf functionality. #255 

**Expected behavior**
Remove flink-protobuf code from the project, use the jar provided by flink.

**Screenshots**

**Additional context**

**Comment by syhily** [comment]
This work has been finished. So we have to close this issue.
