### ISSUE TITLE
[Feature] Add thread-safe test coverage for Pulsar serialization deserialization instances

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#275]
**Is your feature request related to a problem? Please describe.**
Due to instances such as Flink DeserializationSchema, the design is oriented towards single threadedness. The Pulsar Source implementation, on the other hand, uses multiple threads, which leads to thread safety issues. We need to test the PulsarDeserializationSchema implementation class to ensure that it is available in a multi-threaded environment.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
origin issue: #251 
fixed pr: #272 , This pr does not add  thread-safe test.

**Comment by shibd** [comment]
I can fix it. @jianyun8023

**Comment by jianyun8023** [comment]
@shibd  Ok, thanks for your help.

**Comment by syhily** [comment]
Close this for the related issue has been fixed in #275. Tks for your contribution.
