### ISSUE TITLE
[BUG] flink sql case, key will replaced by null ,When the key content is not in the message body

### ISSUE THREAD

**Issue by holmes07** [streamnative/pulsar-flink#278]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jianyun8023** [comment]
Can you add some context to this question? I didn't understand your revision.

**Comment by holmes07** [comment]
Class：DynamicPulsarDeserializationSchema.java 
Method：emitRow

//init key first 
`
        for (int keyPos = 0; keyPos < keyProjection.length; keyPos++) {
                assert physicalKeyRow != null;
                producedRow.setField(keyProjection[keyPos], physicalKeyRow.getField(keyPos));
            }
`

 // here will replace key by null again(if message body without key but ddl defind it)
`       if (physicalValueRow != null) {
                for (int valuePos = 0; valuePos < valueProjection.length; valuePos++) {
                    producedRow.setField(valueProjection[valuePos], physicalValueRow.getField(valuePos));
                }
            }
`
         
To Reproduce
 1.send a message with key : 'key1'  value {id:'1',name:'xxx'}

2. ddl code
**CREATE TABLE user_log (\n" +
                "    id VARCHAR,\n" +
                "    nameVARCHAR,\n" +
                "    key VARCHAR\n" +
                ") WITH (\n" +
                "    'connector' = 'pulsar',\n" +
                "    'topic' = 'persistent://public/default/test',\n" +
                "    'key.format' = 'raw',\n" +
                "    'key.fields' = 'key',\n" +
                "    'value.format' = 'json',\n" +
                "    'value.json.timestamp-format.standard' = 'SQL',\n" +
                "    'scan.startup.mode' = 'external-subscription',\n" +
                "    'scan.startup.sub-name' = 'xxxx',\n" +
                "    'service-url' = 'xxxxx',\n" +
                "    'admin-url' = 'xxxx',\n" +
                "    'properties.client-cache-size' = '20'\n" +
                ")"**

Resolve
 exchange the code will work

**Comment by holmes07** [comment]
**bad case:** send a message with key : 'key1' value {id:'1',name:'xxx'}
**good case:** send a message with key : 'key1' value {id:'1',name:'xxx',key:'key1'}
