### ISSUE TITLE
[FEATURE] support flink batch on connector

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#283]
**Is your feature request related to a problem? Please describe.**

Support for flink bulk mode in the connector.
Pulsar's bulk read capability is being developed, and limited reads are now available using stream mode.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by syhily** [comment]
Close for this is temporarily outdated. This feature should be completed on the new Flink connector after 1.14.
