### ISSUE TITLE
[BUG] failonwrite flag should be set to true by default out of the box

### ISSUE THREAD

**Issue by subbu107** [streamnative/pulsar-flink#312]
**Describe the bug**
Out of the box, the default value of failonwrite flag is false.
This means that out of the box, there  will be data loss if there is a failure to write to sink topic

**To Reproduce**
1. Set up a pipeline with a source and sink topic,  and send data to source topic. Configure pulsar-flink connector with out of the box settings only.
2. restart the brokers randomly, causing some of the pulsar sink writes to fail
3. Data loss is observed.

**Expected behavior**
The default out of the box value of failonwrite should be true to ensure at-least-once processing without changing any ootb values.

**Screenshots**

**Additional context**

**Comment by klwilson227** [comment]
@subbu107 Please use a descriptive issue title.

**Comment by syhily** [comment]
I don't think set `failonwrite` to true as a default value would solve this issue. The main problem is that the data writing lose when some broker is not available. We should have a better re-connection logic for this behavior.

**Comment by jianyun8023** [comment]
This issue will continue to be dealt with in #317.
