### ISSUE TITLE
Can we decouple FlinkPulsarSource's type from Message's?

### ISSUE THREAD

**Issue by Red-Night-Aria** [streamnative/pulsar-flink#331]
pulsar-flink-connector version : 1.12.3

```java
@PublicEvolving
public interface PulsarDeserializationSchema<T> extends PulsarContextAware<T>, Serializable {
...
T deserialize(Message<T> message) throws IOException;
...
}
```

I want to create a `FlinkPulsarSource<T>` to read message from a topic without schema, but the interface method `PulsarDeserializationSchema::deserialize` force me to assign a schema `T` to message first.

I also notice that in 1.11.x version, the interface method is`T deserialize(Message message) throws IOException`, which means Message can have a different type with FlinkPulsarSource.

Is there any approach to avoid the type limitation for pulsar message ? Thanks in advance to anyone who replies.

**Comment by jianyun8023** [comment]
@Red-Night-Aria  The structure of PulsarDeserializationSchema is enough to meet your requirements. Use `PulsarDeserializationSchema.valueOnly(DeserializationSchema<V> valueDeserializer)` to convert bytes to objects.

I do not recommend that you use different data structures in a topic. This is a disaster for business logic.

**Comment by Red-Night-Aria** [comment]
Thank you for your reply! @jianyun8023 

But unfortunately `PulsarDeserializationSchema.valueOnly` can only access message's value. Our business logic also need to use message's property. 

Our demand is to create `FlinkPulsarSource<T>` which T is composed of `message.getData` and `message.getProperty`. In older version of pulsar-flink-connector we can achieve that by below code:
```
public class MyDeserializationSchema implements PulsarDeserializationSchema<Tuple2<String, byte[]>> {
  ....
  @Override
  public Tuple2<String, byte[]> deserialize(Message message) {
     return Tuple2.of(message.getProperty("SomeKey"), message.getData());
  }
  ....
}
``` 
how can we do the same in current version of connector?

**Comment by jianyun8023** [comment]
You can implementation of `DeserializationSchema<Tuple2<String, byte[]>> `, which can return `Tuple2.of(null, bytesData);`, and then you can use `MyDeserializationSchema#deserialize`,
```
Tuple2<String, byte[]> tuple = message.getValue();
tuple.f0 = message.getProperty("SomeKey");
return tuple;
```

**Comment by jianyun8023** [comment]
@Red-Night-Aria If the issue is resolved, can the issue be closed?

**Comment by Red-Night-Aria** [comment]
> @Red-Night-Aria You can implementation of `DeserializationSchema<Tuple2<String, byte[]>> `, which can return `Tuple2.of(null, bytesData);`, and then you can use `MyDeserializationSchema#deserialize`,
> 
> ```
> Tuple2<String, byte[]> tuple = message.getValue();
> tuple.f0 = message.getProperty("SomeKey");
> return tuple;
> ```

yes, that is a workaround. But in my opinion define a dummy class just for implement `DeserializationSchema<Tuple2<String, byte[]>>` interface is too trivail....
Thx anyway~
