### ISSUE TITLE
[BUG] setting 'properties.pulsar.reader.*'  has a bug

### ISSUE THREAD

**Issue by leochinaliu** [streamnative/pulsar-flink#353]
there has a bug when I set ‘properties.pulsar.reader.*’.

eg:

CREATE TABLE pulsar (
  `physical_1` STRING,
  `physical_2` INT,
`eventTime` TIMESTAMP(3) METADATA,
`properties` MAP<STRING, STRING> METADATA ,
`topic` STRING METADATA VIRTUAL,
`sequenceId` BIGINT METADATA VIRTUAL,
`key` STRING ,
`physical_3` BOOLEAN
) WITH (
'connector' = 'pulsar',
  'topic' = 'persistent://public/default/topic1',
  'key.format' = 'json',
  'key.fields' = 'key',
  'value.format' = 'json',
  'service-url' = '',
  'admin-url' = '',
  'properties.pulsar.reader.readCompacted' = 'true',
  'scan.startup.mode' = 'earliest' -- 'external-subscription'
  )

it has a error:  
Unrecognized field "readcompacted" (class org.apache.pulsar.client.impl.conf.ReaderConfigurationData), not marked as ignorable (10 known properties: "cryptoKeyReader", "receiverQueueSize", "subscriptionRolePrefix", "readerListener", "resetIncludeHead", "topicName", "readCompacted", "readerName", "cryptoFailureAction", "keyHashRanges"])
 at [Source: (String)"{"cryptoFailureAction":"FAIL","readcompacted":"true","topicName":"persistent://public/default/topic1-partition-0","readCompacted":false,"resetIncludeHead":true,"receiverQueueSize":1000}

there has tow  'readCompacted' ,  one is 'readCompacted', other is 'readcompacted'.

Describe the solution you'd like
the class 'ConfigurationDataUtils' should be case sensitive when reading  config.

**Comment by gaozhangmin** [comment]
it has been resolved by #329
