### ISSUE TITLE
[BUG] Restore invalid cursor, after automatically reset to the latest position, the first message will be lost.

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#355]
Restore invalid cursor, after automatically reset to the latest position, the first message will be lost.

**It occurs in a newly created topic, and no data has been written. The first message will be lost during consumption.**

**Comment by jianyun8023** [comment]
Restore savepoint, the cursor saved in savepoint no longer exists in pulsar.  Some cursors in pulsar are bigger than him.  At this time, the cursor will be reset to the next readable cursor.  When the linker got the readable cursor, it read the next message and skipped it.

**Comment by jianyun8023** [comment]
@gaozhangmin Can you fix it?

**Comment by gaozhangmin** [comment]
yes, please assign to me.
