### ISSUE TITLE
[BUG] Stream failure if the topic doesn't exist with Pulsar 2.8.0

### ISSUE THREAD

**Issue by eladar2000** [streamnative/pulsar-flink#366]
**Describe the bug**
With a Pulsar 2.8.0 server, a Flink stream containing Pulsar sources or sinks will fail at startup if the topic doesn't exist.

**To Reproduce**
Create a stream with : 
- Flink 1.13.1
- Pulsar 2.8.0
- pulsar-flink connector 1.13.1.0 (probably with the 1.13.1.1 too as the concerned code doesn't seem to have changed, but I havent tried)
- with a Pulsar source linked to a non existant topic
Start the stream
It will fail with this error :
`21/06/29 16:20:26 WARN taskmanager.Task: Source: Custom Source (3/8)#0 (63ad2d64523188db366fd4fbf8970612) switched from INITIALIZING to FAILED with failure cause: org.apache.pulsar.client.admin.PulsarAdminException$NotFoundException: Topic not exist`

**Expected behavior**
If the topic doesn't exist, it should be created at the first connection of the source/sink without error.

**Additional context**
In the PulsarMetadataReader class of the connector, the method getTopicPartitionsAll() try to get the partitions number from Pulsar doing that :
`admin.topics().getPartitionedTopicMetadata(topic.getTopic()).partitions;
`
With Pulsar 2.7.2, if the topic doesn't exist, the admin API response is a HTTP 200 with this content : {"partitions":0}
With Pulsar 2.8.0, if the topic doesn't exist, the admin API response is a HTTP 404 with this content : {"reason":"Topic not exist"} and will raise a PulsarAdminException$NotFoundException and then fail the Stream.

The change in Pulsar 2.8.0 : https://github.com/apache/pulsar/pull/10601

We did this as a workaround (just for our tests) in the flink-connector :
```
int partNum = 0;
try {
   partNum = admin.topics().getPartitionedTopicMetadata(topic.getTopic()).partitions;
} catch (PulsarAdminException.NotFoundException ignored) {}
```
but there are probably other impacts in the connector, like in this method of the same class :
```
    public boolean topicExists(String topicName) throws PulsarAdminException {
        int partitionNum = admin.topics().getPartitionedTopicMetadata(topicName).partitions;
        if (partitionNum > 0) {
            return true;
        } else {
            admin.topics().getStats(topicName);
        }
        return true;
    }
```
 this method will probably fail too and never return false

**Comment by shibd** [comment]
@jianyun8023 I can fix it.

**Comment by shibd** [comment]
So, Does pulsar allow one topic `partitions = 0` ?   

This code gets the `partitions = 0` in pulsar 2.8.
```
        String topicName = "metadate3";
        try {
            PulsarClient client = PulsarClient.builder().serviceUrl(adminUrl).build();
            client.newProducer(Schema.STRING).topic(topicName).create();

            PartitionedTopicMetadata test21 = pulsarAdmin.topics().getPartitionedTopicMetadata(topicName);
            System.out.println(test21.partitions);  // partitions = 0
            
        } catch (PulsarAdminException e) {
            e.printStackTrace();
        }
```

Is this the problem of pulsar?  @jianyun8023
