### ISSUE TITLE
[BUG] Repeat consumption last message

### ISSUE THREAD

**Issue by gaozhangmin** [streamnative/pulsar-flink#367]
When `external-subscription` mode used, caused repeat consumption.

**Comment by gaozhangmin** [comment]
I will fixing it

**Comment by jianyun8023** [comment]
This problem occurs in the following versions:
- 1.13.1.1
- 1.12.4.2
- 1.11.1.4
- 2.4.28.7

**Comment by jianyun8023** [comment]
When pulsar flink submitted the cursor to the pulsar broker, the submitted cursor did not comply with the pulsar specification, resulting in the actual cursor being `cursor -1`. When pulsar flink uses subscriber initialization, the first message is skipped.
After fixing #363, the logic of skipping a message was removed. This leads to the problem.
