### ISSUE TITLE
[FEATURE] pulsar-flink-sql-connector_2.11 support flink 1.12.2

### ISSUE THREAD

**Issue by haormj** [streamnative/pulsar-flink#377]
**Is your feature request related to a problem? Please describe.**
pulsar-flink-sql-connector_2.11 not support flink 1.12.2

when I use flink 1.12.2 and io.streamnative.connectors:pulsar-flink-sql-connector_2.11:1.12.4.2

it will tips Unrecognized field "readername"

**Describe the solution you'd like**
support 1.12.2

**Comment by syhily** [comment]
@jianyun8023 I think this is a bug. Can you confirm it?

**Comment by jianyun8023** [comment]
@haormj @syhily I don't think this should be a bug. flink 1.12.4 and 1.12.2 are theoretically compatible and should work. If not compatible, try using the `pulsar-flink-origin` module and exclude the flink dependencies.
For `readername` more detailed information is needed to analyze it.

**Comment by jianyun8023** [comment]
@haormj Has this problem been solved? If so, I will close this issue.

**Comment by syhily** [comment]
Close for outdated. PING me if you still have questions on this issue.
