### ISSUE TITLE
[BUG] Flink-pulsar-connector consume topic's message backlog increasedly, but topic's msgRateIn equal msgRateOut

### ISSUE THREAD

**Issue by ganymedewuke** [streamnative/pulsar-flink#389]
Flink-pulsar-connector consume topic's message backlog increasedly, but topic's msgRateIn equals msgRateOut
1、Flink's checkpointInterval 60s ， message backlog was 2660 in the beginning
2、After 2 houres message backlog was 4350 
3、After 6 houres message backlog was 6000 
4、It this time ， topic's msgRateIn equals msgRateOut 
5、But topic's msgBacklog  increasedly. 
6、Flink-pulsar-connector's version is 1.12.4.1, flink'version is 1.12.4 and pulsar-client's version is 2.7.2

**Comment by syhily** [comment]
After reading your issue, I don't think this is a bug. `msgRateIn` equals `msgRateOut` means that the consuming speed is equal to producing speed. But the real condition is more complex.

Pulsar should write the data into Bookie for at least 3 replicates. Then the message can be consumed by the consumer. The consumer internally has a buffer queue for incoming messages. The real consumption is just picking the message from the queue.

We would stat the `msgRateOut` by counting the messages which have been sent to the consumer subscription queue buffer. This doesn't mean these messages have been processed and acknowledge. This is the reason why you keep seeing the topic's msgBacklog growing in monitor page.

**Comment by syhily** [comment]
Closed for the comment above. PING me if you still have any questions about it.
