### ISSUE TITLE
[FEATURE] Support for consumer subscriptions

### ISSUE THREAD

**Issue by lonerzzz** [streamnative/pulsar-flink#406]
**Is your feature request related to a problem? Please describe.**
I am upgrading from a previous unsupported implementation of a Pulsar Flink connector and in migrating the code, I have not found a way to support consumer subscriptions to streams. This is a rather fundamental feature set that is very useful and should exist.

**Describe the solution you'd like**
The connector should support the underlying Pulsar feature of multiple consumer subscriptions to a stream

**Describe alternatives you've considered**
I have looked at sequential processing of the stream in a daisy chain mode, but some processing is for lower latency and other processing requires more effort so the two should not be on the same flow

**Additional context**
None

**Comment by syhily** [comment]
This feature has been completed on the Flink repository. Can you check [it](https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/connectors/datastream/pulsar/)?

**Comment by syhily** [comment]
Close this issue for no response from the reporter. Feel free to PING if you still have any questions.
