### ISSUE TITLE
[FEATURE] Enable the use of sticky key-range reader

### ISSUE THREAD

**Issue by yjshen** [streamnative/pulsar-flink#42]
We could support sub-stream parallelism by using the sticky key-range reader.

https://github.com/apache/pulsar/pull/5928

**Comment by yjshen** [comment]
After throughout discussion with @codelipenghui, current sticky consumer lacks three main capabilities:

- to create a consumer with immutable key-range at start time.
- enable consumption without the need to ack messages.
- the subscription seems to be different from that created from admin.topics.createSubscription()

**Comment by codelipenghui** [comment]
@yjshen 
I noticed @jiazhai add support for exposing subscription mode at the consumer side. So that we can create a consumer with a non-durable subscription, it's more like a reader.

And I forgot that the sticky consumer is supported, so to create a consumer with immutable key-range we can use

**Comment by jianyun8023** [comment]
pr #58 has completed this function.
