### ISSUE TITLE
[BUG] There is a possibility of insufficient permissions to upload schema in Sink

### ISSUE THREAD

**Issue by yuruguo** [streamnative/pulsar-flink#427]
**Describe the bug**
The schema needs to be upload before building Pulsar Producer in `FlinkPulsarSinkBase`, as below:
https://github.com/streamnative/pulsar-flink/blob/f86ad8681b9c29a2b1a01f6827250f16eabbe521/pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarSinkBase.java#L320-L322
https://github.com/streamnative/pulsar-flink/blob/f86ad8681b9c29a2b1a01f6827250f16eabbe521/pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarSinkBase.java#L267-L269

but the `uploadSchema` is done by `PulsarAdmin`, as below:
https://github.com/streamnative/pulsar-flink/blob/f86ad8681b9c29a2b1a01f6827250f16eabbe521/pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/SchemaUtils.java#L59
https://github.com/streamnative/pulsar-flink/blob/f86ad8681b9c29a2b1a01f6827250f16eabbe521/pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/SchemaUtils.java#L79

 If the `token` in PulsarAdmin is not a `super-user`(for example, the `token` only has the permission to produce and consume a topic), then there will be insufficient permissions.

In fact, `uploadSchema` is a redundant operation, because the producer will automatically update the topic schema when writing data.

**To Reproduce**
Flink Job code as shown:
![image](https://user-images.githubusercontent.com/13013780/137714142-87dc0d76-1d8b-4c88-9e6c-c14f78712eaa.png)
A exception occurred during execution, as below: 
![image](https://user-images.githubusercontent.com/13013780/137713949-3d0458d8-733a-4aa0-98eb-64179e5a2fe8.png)

**Comment by yuruguo** [comment]
> @yuruguo
> 
> The permission is managed by Pulsar cluster admin. In this case of lacking schema management permission, the behavior is expected.
> 
> You mentioned a good point of redundant operations, which we may investigate how to reduce it.
> 
> BTW, the exception screen shot you added here says 404, which means not found. I guess the topic is not created properly?

In fact, `404` is not mean that topic or related resource not exist, it causes by authorization, sorce code
https://github.com/apache/pulsar/blob/1eb08f3136dbe96e473b63038da9337043be7a0d/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java#L314

**Comment by syhily** [comment]
@nlu90 After investigating this issue, I think the fix by @yuruguo is awesome. I have merged the related PR.

**Comment by syhily** [comment]
Closed by #428
