### ISSUE TITLE
Check the topic's markDeletePosition and readPosition are very different

### ISSUE THREAD

**Issue by zxybl** [streamnative/pulsar-flink#438]
Use the reader of flink-pulsar to view the topic's markDeletePosition and readPosition are very different. The log shows Successfully committed offset255271:4691:6:0 to topic, why is markDeletePosition not updated?
![pulsar-reader](https://user-images.githubusercontent.com/49438782/138660185-fb669b95-6064-413a-a88c-ad0e615ac8bd.jpg)

**Comment by syhily** [comment]
Hi @zxybl, Are the subscription name `reader-535bc6d916` provided by the method `FlinkPulsarSource.setStartFromSubscription`?

**Comment by syhily** [comment]
FYI, this may be a bug from [Pulsar side](https://github.com/apache/pulsar/pull/12343/files).

**Comment by zxybl** [comment]
> 嗨@zxybl，`reader-535bc6d916`该方法提供订阅名称`FlinkPulsarSource.setStartFromSubscription`吗？
> 
> 此方法的默认订阅位置为`MessageId.latest`。如果您使用`MessageId.earliest`或 ，我们不会将偏移量提交给 Pulsar `MessageId.latest`。@jianyun8023你能确认一下吗？
> 
> ```java
> public  void commitOffsetToPulsar(
>          Map< TopicRange , MessageId > offset,
>          PulsarCommitCallback offsetCommitCallback) 抛出InterruptedException {
> 
>     doCommitOffsetToPulsar(removeEarliestAndLatest(offset), offsetCommitCallback);
> }
> ```

**Comment by zxybl** [comment]
> 嗨@zxybl，`reader-535bc6d916`该方法提供订阅名称`FlinkPulsarSource.setStartFromSubscription`吗？
> 
> 此方法的默认订阅位置为`MessageId.latest`。如果您使用`MessageId.earliest`或 ，我们不会将偏移量提交给 Pulsar `MessageId.latest`。@jianyun8023你能确认一下吗？
> 
> ```java
> public  void commitOffsetToPulsar(
>          Map< TopicRange , MessageId > offset,
>          PulsarCommitCallback offsetCommitCallback) 抛出InterruptedException {
> 
>     doCommitOffsetToPulsar(removeEarliestAndLatest(offset), offsetCommitCallback);
> }
> ```

我使用了FlinkPulsarSource.setStartFromLatest()，并没有使用FlinkPulsarSource.setStartFromSubscription。

**Comment by syhily** [comment]
@zxybl Tks for your information. This is a known bug on the Pulsar side. We are waiting for the fix by Pulsar developer.
