### ISSUE TITLE
Catalog Redesign and Implementation

### ISSUE THREAD

**Issue by nlu90** [streamnative/pulsar-flink#446]
The current implementation of catalog mixed concepts and is very limited to support use cases such as: query via a regex subscription, customize the setting of pulsar client options etc. We need to clearly design a new catalog that serve the following two purpose:

1. can help user easily access topics inside the pulsar cluster
2. can serve a meta store that save flink database/table definitions for advanced queries.

- [ ] Design Doc (TO BE ADDED)
- [ ] Implementation Tasks
       - [ ] task1
       ....
- [ ] Releases
        - [ ] 1.12
        - [ ] 1.13
- [ ] Master branch code change

**Comment by syhily** [comment]
The [design draft](https://docs.google.com/document/d/1JrItXy0H-gUITZFDKLTlADE1IoTK-Mkf5yBCsMfRV8k) has been published by @nlu90
