### ISSUE TITLE
[BUG] job canceled,Failed to cancel the pulsar, Failed to remove cursor or TopicRange

### ISSUE THREAD

**Issue by wjcwin** [streamnative/pulsar-flink#449]
**Describe the bug**
flink  version 1.13.1
pulsar version  2.5.0
pulsar-flink-connector_2.11  version 1.13.1.0
run with flink standalone cluster 
flink job is a source connector job, when one of taskmanager restart cause oom, the job canceled,but throw one ERROR,:
```
ERROR org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource [] - Failed to cancel the pulsar Fetcher java.lang.RuntimeException:  Failed to remove cursor or TopicRange[topic=persistent://xxxxx/xxxx/xxxx-partition-2, key-range=SerializableRange{range=[0,65535]}]
      at org.apache.flink.steraming.connectors.pulsar.inernal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:278)
      ...... 
Caused by: org.apache.pulsar.client.admin.PUlsarAdminException:java.lang.InterruptedException
      ......6 more
```
when start  the flink job again ,i got this
```
org.apache.pulsar.clint.api.PulsarClientException$ConsumerBusyException: Exclusive consumer  is already connected
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by syhily** [comment]
Can you upgrade your pulsar version? The connector 1.13.1.0 is designed to be used on Pulsar 2.7.0 or above.

**Comment by syhily** [comment]
No response from the reporter, close this. @wjcwin You can PING me if you still suck with this issue.
