### ISSUE TITLE
Unable to serialize a case class with Option type fields

### ISSUE THREAD

**Issue by aaraujo86** [streamnative/pulsar-flink#453]
I'm currently trying to use Pulsar as a sink and when serializing a scala case class with a Option type field I'm getting the following error:

`org.apache.pulsar.shade.org.apache.avro.SchemaParseException: Illegal character in: None$`

Case class I'm using for testing:

```
case class Car(
                name: String,
                model: Option[Long]
              )
```

And this is how I'm currently setting up the Pulsar sink:

   ```
 val serializer = new PulsarSerializationSchemaWrapper.Builder[Car](AvroSer.of(classOf[Car]))
      .usePojoMode(classOf[Car], RecordSchemaType.AVRO)
      .build()

    val clientConfigurationData = new ClientConfigurationData()
    clientConfigurationData.setServiceUrl(serviceUrl)

    val sink = new FlinkPulsarSink[Car](
        adminUrl,
        Optional.of(topic),
        clientConfigurationData,
        new Properties(),
        serializer,
        PulsarSinkSemantic.AT_LEAST_ONCE
      )
```

I've tried a few different ways but them all seem to throw some sort of error. If I just remove the option field the code just works. I wonder if there is any way around this issue.

Thanks in advance.

**Comment by syhily** [comment]
Hi @aaraujo86, it seems like you are using a Scala case class with Avro?
We are mainly working on Java 8 and don't test this situation. I think you may need to implement custom SerializationSchema by using [avro4s](https://github.com/sksamuel/avro4s#built-in-type-mappings)

**Comment by syhily** [comment]
BTW. A java pojp class with `Optional` field didn't meet the parsing exception. Can you change your case class to a Java pojo class?

```java
public class AvroSerTest {

    public static class A {
        Optional<String> some;

        public Optional<String> getSome() {
            return some;
        }

        public void setSome(Optional<String> some) {
            this.some = some;
        }
    }

    public static void main(String[] args) {
        AvroSer<A> avroSer = AvroSer.of(A.class);
        A message = new A();
        message.setSome(Optional.of("Some"));
        avroSer.serialize(message);

        message.setSome(Optional.empty());
        avroSer.serialize(message);
    }
}
```

**Comment by syhily** [comment]
Closed for this is not a connector issue. Users can implement a custom serializer. The default avro don't support scala case class with `Option` field.

**Comment by syhily** [comment]
If you have any questions, just simply add comments.
