### ISSUE TITLE
[BUG] subscription name not take effect in flink SQL Job with release-1.13/master branch

### ISSUE THREAD

**Issue by KevinyhZou** [streamnative/pulsar-flink#457]
**Describe the bug**
I create a flink sql job to consume data from pulsar topic, and the DDL like this
create table test_in(
  name string,
  proctime as PROCTIME()
) with (
  'connector' = 'pulsar',
  'topic' = 'persistent://public/default/test_bigoflow_in',
  'value.format' = 'csv',
  'service-url' = '',
  'admin-url' = '',
  'scan.startup.mode' = 'external-subscription',
  'scan.startup.sub-name' = 'bcd123'
);
....
and i start the job, from the log i find the subscription name not 'bcd123', which i set in ddl , but as below
![image](https://user-images.githubusercontent.com/37431499/140924608-f8c0ba44-9612-4f39-88f7-72ee13d68635.png)

**To Reproduce**
create a flink sql job and set the startup mode as external-subscription, and set subscription name, when the job is started.  look the log of taskmanager to find the subscription name,  then the problem will appear.

**Expected behavior**
the subscription name of the topic is start with 'scan.startup.sub-name' set in DDL. 

**Screenshots**

**Additional context**

**Comment by jianyun8023** [comment]
@KevinyhZou @syhily  This is the correct behavior.

In subscription mode it will use the subscriber you set `bcd123` to get the cursor and then use that cursor for consumption. On checkpoint completion, the current cursor will be updated to the subscriber `bcd123 ` .

The source implementation uses the Pulsar Reader API for consumption and is in exclusive mode, so it is not recommended to set this subscription name directly. If you wish to set the prefix of the subscription, you can set `'properties.pulsar.reader.subscription-role-prefix' = 'bcd123-'` in SQL. For more parameters in reader, you can refer to [Pulsar Reader API](https://pulsar.apache.org/docs/en/client-libraries-java/#reader).

> Due to Flink SQL limitation, the configuration needs to be converted from `receiverQueueSize` format to `receiver-queue-size` format. For example `receiverQueueSize` is defined in SQL as `properties.pulsar.reader.receiver-queue-size `.

**Comment by syhily** [comment]
Closed for this is a known feature.
