### ISSUE TITLE
[BUG] Using sql does not create the expected Topic

### ISSUE THREAD

**Issue by jianyun8023** [streamnative/pulsar-flink#478]
**Describe the bug**
In the current master, the behavior of getting topic in Table is modified. This caused an error and the topic parameter was not handled correctly when creating a table using SQL.

When using the following SQL
```sql
CREATE TABLE topicA ( 
  `k_user_id` BIGINT,
   ...
   ) WITH (
   'connector' = 'pulsar',
   'topic' = 'persistent://public/default/topic82547611',
   'admin-url' = 'http://localhost:8080',
   'service-url' = 'pulsar://localhost:6650'
 )
```
I want to create the topic `persistent://public/default/topic82547611`, but I get the error format of TopicName `default_catalog.default_database.topicA`.

**Comment by jianyun8023** [comment]
In Flink, there are two ways to create a table:
1. directly through SQL.
2. Use Catalog to create Table automatically.

In both ways, the Table object created is `CatalogTable`. But there are some differences in the parameters.
The main fields of CatalogTable are `catalogName`, `databaseName`, `objectName`, `properties`, `schema`, etc.
**There are two sources for topic name generation `databaseName+ objectName` or `properties#topic`**
- Directly by SQL.
   - catalogName, databaseName values are default (`default_catalog`,`default_database`), objectName is the table name, properties exist in the custom topic property.
- Creating a table via Catalog
  - The catalogName, databaseName, and objectName values are the currently used catalog information, and there may be custom topic properties in the properties.

The two cases have different logic.
- When creating a Table directly using SQL, you can only get the topic using `properties#topic`.
- When creating a Table using Catalog, `catalogName.databaseName.objectName` is preferred as the Topic name, and if the user configures `properties#generic`, then `properties#topic` is used.

**The current code implementation ignores the scenario of creating a Table directly using SQL.**
```
private List<String> generateTopic(ObjectIdentifier table, ReadableConfig tableOptions) {
        List<String> topics = null;
        if (tableOptions.get(GENERIC)) {
            topics = tableOptions.getOptional(TOPIC).orElse(null);
        } else {
            String rawTopic = table.getDatabaseName() + "/" + table.getObjectName();
            final String topic = TopicName.get(rawTopic).toString();
            topics = Collections.singletonList(topic);
        }

        return topics;
    }
```

So this current problem has occurred.

**Comment by jianyun8023** [comment]
@nlu90 @syhily Please help to solve this problem.

**Comment by imaffe** [comment]
Closing this issue because the described behaviour is expected as per discussion

**Comment by imaffe** [comment]
> @imaffe Can you elaborate more on as per what discussion happened where? I'm experiencing the same issue. If it's expected behavior, why it's not mentioned in readme?

Basically, the `topic` option in WITH clause does not specify a topic to create, instead, it means map an existiing pulsar topic to the Flink table named "topicA" in this case. So the use case is actually map an existing pulsar topic ('persistent://public/default/topic82547611' in this case) to a Flink table (named "topicA" in this case). The doc is not clear on this but this use case is similar to Kafka connector.

**Comment by jianyun8023** [comment]
@longtengz You can add `generic=true` to the with block to use the topic parameter, which is a temporary solution.

@imaffe Your understanding is not correct. Kafka does not have a catalog schema and there is no use of `topicA` behavior. The ability for tables to use the topic parameter is broken in the catalog support we added.
