### ISSUE TITLE
[BUG] Pulsar client issue causing unacknowledged messages.

### ISSUE THREAD

**Issue by mattisonchao** [streamnative/pulsar-flink#552]
**Describe the bug**

I checked the connector related to `Flink-1.13` and found that the latest stable `pulsar-flink-connector` release is `1.13.1.4`. But its internal client version is 2.8.0.

PR https://github.com/apache/pulsar/pull/12853 describes some issues. One of them is that because the `flush` task was cancelled by exception, it will not continue to send acknowledgement messages.

**Screenshots**
```java
"reader-a19805af61" : {
      "markDeletePosition" : "19662:41006",
      "readPosition" : "19707:30913",
      "waitingReadOp" : false,
      "pendingReadOps" : 0,
      "messagesConsumedCounter" : 7890298,
      "cursorLedger" : -1,
      "cursorLedgerLastEntry" : -1,
      "individuallyDeletedMessages" : "[]",
      "lastLedgerSwitchTimestamp" : "2022-03-24T09:55:54.085Z",
      "state" : "Uninitialized",
      "numberOfEntriesSinceFirstNotAckedMessage" : 2039907,
      "totalNonContiguousDeletedMessagesRange" : 0,
      "subscriptionHavePendingRead" : false,
      "subscriptionHavePendingReplayRead" : false,
      "properties" : { }
    }
```
**Solution**

We should release a new version based on `release-1.13`, since its pulsar client version is 2.8.3 and it already contains this patch.

**Comment by nlu90** [comment]
You can use: 

https://search.maven.org/artifact/io.streamnative.connectors/pulsar-flink-connector-origin/1.13.6.0-rc2/jar

or

https://search.maven.org/artifact/io.streamnative.connectors/pulsar-flink-connector_2.12/1.13.6.1-rc4/jar


These release contains the 2.8.3 pulsar client
