### ISSUE TITLE
[QUESTION] How does this project relate to apache pulsar flink connector

### ISSUE THREAD

**Issue by nikolasten** [streamnative/pulsar-flink#598]
What is the relation of this project to apache pulsar connector?
https://github.com/apache/flink/tree/master/flink-connectors/flink-connector-pulsar

Codebase looks quite different. Which one should we use?

**Comment by nlu90** [comment]
@nikolasten 

If you are using Flink 1.15 or newer, upstream Flink's pulsar connector should be used.

If you are using Flink 1.14 or older, this legacy connector should be used.
