### ISSUE TITLE
Release pulsar-flink connector for scala 2.12

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-flink#80]
*Motivation*

Currently the pulsar-flink connector is released with scala 2.11. We might need to release the connector with 2.12 as well.

**Comment by jiazhai** [comment]
![image](https://user-images.githubusercontent.com/6348208/82787401-e4db0d00-9e98-11ea-96dd-bca64a967302.png)
will need to build and release for both scala 2.11 and 2.12
