### ISSUE TITLE
Option to specify start message Id when the specified message Id is invalid

### ISSUE THREAD

**Issue by sindhushreem** [streamnative/pulsar-flink#82]
**Is your feature request related to a problem? Please describe.**
There are multiple scenarios which can cause messageId persisted in savepoint/checkpoint to be invalid. Few examples :  1. The persistent store in pulsar is recreated because of system failures 2. The topic was recreated because of accidental deletion of topic. There should be options in connector ( like auto.offset.reset in Kafka) to indicate the start offset when the messageId in Flink savepoint/checkpoint is no longer valid in Pulsar.

**Describe the solution you'd like**
auto.offset.reset flag 

**Describe alternatives you've considered**

**Additional context**

**Comment by jiazhai** [comment]
Thanks for opening this issue, We will handle this issue this week.

**Comment by jiazhai** [comment]
This feature not supported in checkpoint, need to add it. @yjshen to help on this.

**Comment by jiazhai** [comment]
@sindhushreem, Looked into current cursor reset logic in Pulsar, It should be worked well for reset read position to an expired/deleted MessageId. 
If the target messageId is smaller than any of the current messageIds in topic, the final position after resetting will be the earliest messageId; while if the target messageId is invalid or bigger than any of the messageIds in topic, the final position after resetting will be the latest position.

**Comment by sijie** [comment]
Close this issue since this is already available in current Pulsar.
