### ISSUE TITLE
[FEATURE] Support reading from compacted topic

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-flink#88]
*Motivation*

Currently, the Flink connector doesn't support reading from compacted topic. We need to support this feature.

**Comment by Huanli-Meng** [comment]
I think the doc should be updated if the issue is fixed. right? @sijie

**Comment by sijie** [comment]
I think the feature is already there. We need to update the documentation.

**Comment by Huanli-Meng** [comment]
@sijie , any background info about this feature? Thanks.

**Comment by Huanli-Meng** [comment]
@sijie , any PR about this feature to facilitate tracking the background information? Thanks

**Comment by reswqa** [comment]
move this feature to #184 and close this issue because that issue have more detail context.
